version: '3'

services:
  admin-frontend:
    build: ./admin-frontend
    command: npm run dev
    ports:
      - "5173:5173"
    volumes:
      - ./admin-frontend:/usr/src/app

  music:
    build:
      context: ./music_vs_store/
      dockerfile: Dockerfile.dev
    command: air -c .air.toml
    volumes:
      - ./music_vs_store:/usr/src/music

  nginx: 
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/default.conf
