version: '3'

services:

  db:
    image: postgres:12-alpine
    container_name: music_vs_store_db
    restart: unless-stopped
    shm_size: 128mb
    volumes: 
      - ./db/postgres_db:/var/lib/postgresql/data
    ports:
      - 1234:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - music_vs_store_network
        
  admin-frontend:
    container_name: music_vs_store_admin-frontend
    build: ./admin-frontend
    command: npm run preview
    restart: unless-stopped
    depends_on:
      - music
      - db
    ports:
      - "4173:4173"
    networks:
      - music_vs_store_network

  music:
    build: ./music_vs_store
    container_name: music
    command: /usr/local/bin/music/music_vs_store
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - SERVER_PORT=:3002
      - DB_SOURCE=postgresql://admin:admin@db:5432/postgres_db?sslmode=disable
      - DB_DRIVER=postgres
    ports:
      - 3002:3002
    networks:
      - music_vs_store_network

  nginx:
    container_name: music_vs_store_nginx
    image: nginx:stable-alpine
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/default.conf
    depends_on:
      - admin-frontend
      - music
    networks:
      - music_vs_store_network

networks:
  music_vs_store_network:
    driver: bridge
